/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTobeIndexRouteImport } from './routes/_authenticated/tobe.index'
import { Route as AuthenticatedRoadmapIndexRouteImport } from './routes/_authenticated/roadmap.index'
import { Route as AuthenticatedRelatoriosIndexRouteImport } from './routes/_authenticated/relatorios.index'
import { Route as AuthenticatedRelatorioAcompanhamentoIndexRouteImport } from './routes/_authenticated/relatorio-acompanhamento.index'
import { Route as AuthenticatedProjetosIndexRouteImport } from './routes/_authenticated/projetos.index'
import { Route as AuthenticatedProcessosIndexRouteImport } from './routes/_authenticated/processos.index'
import { Route as AuthenticatedPriorizacaoIndexRouteImport } from './routes/_authenticated/priorizacao.index'
import { Route as AuthenticatedPlanosAcaoIndexRouteImport } from './routes/_authenticated/planos-acao.index'
import { Route as AuthenticatedOportunidadesIndexRouteImport } from './routes/_authenticated/oportunidades.index'
import { Route as AuthenticatedIndicadoresIndexRouteImport } from './routes/_authenticated/indicadores.index'
import { Route as AuthenticatedHorasIndexRouteImport } from './routes/_authenticated/horas.index'
import { Route as AuthenticatedEntrevistasIndexRouteImport } from './routes/_authenticated/entrevistas.index'
import { Route as AuthenticatedDiagnosticoIndexRouteImport } from './routes/_authenticated/diagnostico.index'
import { Route as AuthenticatedCronoanaliseIndexRouteImport } from './routes/_authenticated/cronoanalise.index'
import { Route as AuthenticatedControleIndexRouteImport } from './routes/_authenticated/controle.index'
import { Route as AuthenticatedCausaRaizIndexRouteImport } from './routes/_authenticated/causa-raiz.index'
import { Route as AuthenticatedCalendarioIndexRouteImport } from './routes/_authenticated/calendario.index'
import { Route as AuthenticatedAnaliseCriticaIndexRouteImport } from './routes/_authenticated/analise-critica.index'
import { Route as AuthenticatedProjetosIdRouteImport } from './routes/_authenticated/projetos.$id'
import { Route as AuthenticatedProcessosIdRouteImport } from './routes/_authenticated/processos.$id'
import { Route as AuthenticatedMapasInformacaoRouteImport } from './routes/_authenticated/mapas.informacao'
import { Route as AuthenticatedMapasDoresRouteImport } from './routes/_authenticated/mapas.dores'
import { Route as AuthenticatedMapasDecisaoRouteImport } from './routes/_authenticated/mapas.decisao'
import { Route as AuthenticatedFaseSlugRouteImport } from './routes/_authenticated/fase.$slug'
import { Route as AuthenticatedEntrevistasNovaRouteImport } from './routes/_authenticated/entrevistas.nova'
import { Route as AuthenticatedEntrevistasIdRouteImport } from './routes/_authenticated/entrevistas.$id'
import { Route as AuthenticatedDiagnosticoIdRouteImport } from './routes/_authenticated/diagnostico.$id'
import { Route as AuthenticatedCronoanaliseNovaRouteImport } from './routes/_authenticated/cronoanalise.nova'
import { Route as AuthenticatedCronoanaliseIdRouteImport } from './routes/_authenticated/cronoanalise.$id'
import { Route as AuthenticatedCausaRaizIdRouteImport } from './routes/_authenticated/causa-raiz.$id'
import { Route as AuthenticatedProjetosIdIndexRouteImport } from './routes/_authenticated/projetos.$id.index'
import { Route as ApiPublicPlanosTokenRouteImport } from './routes/api/public/planos.$token'
import { Route as ApiPublicColetasTokenRouteImport } from './routes/api/public/coletas.$token'
import { Route as AuthenticatedProjetosIdMelhoriasRouteImport } from './routes/_authenticated/projetos.$id.melhorias'
import { Route as AuthenticatedProjetosIdMapeamentoRouteImport } from './routes/_authenticated/projetos.$id.mapeamento'
import { Route as AuthenticatedProjetosIdGestaoRouteImport } from './routes/_authenticated/projetos.$id.gestao'
import { Route as AuthenticatedProjetosIdExecucaoRouteImport } from './routes/_authenticated/projetos.$id.execucao'
import { Route as AuthenticatedProjetosIdEncerramentoRouteImport } from './routes/_authenticated/projetos.$id.encerramento'
import { Route as AuthenticatedProjetosIdDiagnosticoRouteImport } from './routes/_authenticated/projetos.$id.diagnostico'
import { Route as AuthenticatedProcessosSugerirInterviewIdRouteImport } from './routes/_authenticated/processos.sugerir.$interviewId'
import { Route as AuthenticatedIndicadoresIdColetarRouteImport } from './routes/_authenticated/indicadores.$id.coletar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTobeIndexRoute = AuthenticatedTobeIndexRouteImport.update({
  id: '/tobe/',
  path: '/tobe/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapIndexRoute =
  AuthenticatedRoadmapIndexRouteImport.update({
    id: '/roadmap/',
    path: '/roadmap/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosIndexRoute =
  AuthenticatedRelatoriosIndexRouteImport.update({
    id: '/relatorios/',
    path: '/relatorios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatorioAcompanhamentoIndexRoute =
  AuthenticatedRelatorioAcompanhamentoIndexRouteImport.update({
    id: '/relatorio-acompanhamento/',
    path: '/relatorio-acompanhamento/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetosIndexRoute =
  AuthenticatedProjetosIndexRouteImport.update({
    id: '/projetos/',
    path: '/projetos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcessosIndexRoute =
  AuthenticatedProcessosIndexRouteImport.update({
    id: '/processos/',
    path: '/processos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPriorizacaoIndexRoute =
  AuthenticatedPriorizacaoIndexRouteImport.update({
    id: '/priorizacao/',
    path: '/priorizacao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanosAcaoIndexRoute =
  AuthenticatedPlanosAcaoIndexRouteImport.update({
    id: '/planos-acao/',
    path: '/planos-acao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOportunidadesIndexRoute =
  AuthenticatedOportunidadesIndexRouteImport.update({
    id: '/oportunidades/',
    path: '/oportunidades/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndicadoresIndexRoute =
  AuthenticatedIndicadoresIndexRouteImport.update({
    id: '/indicadores/',
    path: '/indicadores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHorasIndexRoute = AuthenticatedHorasIndexRouteImport.update({
  id: '/horas/',
  path: '/horas/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntrevistasIndexRoute =
  AuthenticatedEntrevistasIndexRouteImport.update({
    id: '/entrevistas/',
    path: '/entrevistas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiagnosticoIndexRoute =
  AuthenticatedDiagnosticoIndexRouteImport.update({
    id: '/diagnostico/',
    path: '/diagnostico/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCronoanaliseIndexRoute =
  AuthenticatedCronoanaliseIndexRouteImport.update({
    id: '/cronoanalise/',
    path: '/cronoanalise/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedControleIndexRoute =
  AuthenticatedControleIndexRouteImport.update({
    id: '/controle/',
    path: '/controle/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCausaRaizIndexRoute =
  AuthenticatedCausaRaizIndexRouteImport.update({
    id: '/causa-raiz/',
    path: '/causa-raiz/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarioIndexRoute =
  AuthenticatedCalendarioIndexRouteImport.update({
    id: '/calendario/',
    path: '/calendario/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnaliseCriticaIndexRoute =
  AuthenticatedAnaliseCriticaIndexRouteImport.update({
    id: '/analise-critica/',
    path: '/analise-critica/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetosIdRoute = AuthenticatedProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcessosIdRoute =
  AuthenticatedProcessosIdRouteImport.update({
    id: '/processos/$id',
    path: '/processos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMapasInformacaoRoute =
  AuthenticatedMapasInformacaoRouteImport.update({
    id: '/mapas/informacao',
    path: '/mapas/informacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMapasDoresRoute = AuthenticatedMapasDoresRouteImport.update({
  id: '/mapas/dores',
  path: '/mapas/dores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapasDecisaoRoute =
  AuthenticatedMapasDecisaoRouteImport.update({
    id: '/mapas/decisao',
    path: '/mapas/decisao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFaseSlugRoute = AuthenticatedFaseSlugRouteImport.update({
  id: '/fase/$slug',
  path: '/fase/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntrevistasNovaRoute =
  AuthenticatedEntrevistasNovaRouteImport.update({
    id: '/entrevistas/nova',
    path: '/entrevistas/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrevistasIdRoute =
  AuthenticatedEntrevistasIdRouteImport.update({
    id: '/entrevistas/$id',
    path: '/entrevistas/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiagnosticoIdRoute =
  AuthenticatedDiagnosticoIdRouteImport.update({
    id: '/diagnostico/$id',
    path: '/diagnostico/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCronoanaliseNovaRoute =
  AuthenticatedCronoanaliseNovaRouteImport.update({
    id: '/cronoanalise/nova',
    path: '/cronoanalise/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCronoanaliseIdRoute =
  AuthenticatedCronoanaliseIdRouteImport.update({
    id: '/cronoanalise/$id',
    path: '/cronoanalise/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCausaRaizIdRoute =
  AuthenticatedCausaRaizIdRouteImport.update({
    id: '/causa-raiz/$id',
    path: '/causa-raiz/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetosIdIndexRoute =
  AuthenticatedProjetosIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjetosIdRoute,
  } as any)
const ApiPublicPlanosTokenRoute = ApiPublicPlanosTokenRouteImport.update({
  id: '/api/public/planos/$token',
  path: '/api/public/planos/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicColetasTokenRoute = ApiPublicColetasTokenRouteImport.update({
  id: '/api/public/coletas/$token',
  path: '/api/public/coletas/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjetosIdMelhoriasRoute =
  AuthenticatedProjetosIdMelhoriasRouteImport.update({
    id: '/melhorias',
    path: '/melhorias',
    getParentRoute: () => AuthenticatedProjetosIdRoute,
  } as any)
const AuthenticatedProjetosIdMapeamentoRoute =
  AuthenticatedProjetosIdMapeamentoRouteImport.update({
    id: '/mapeamento',
    path: '/mapeamento',
    getParentRoute: () => AuthenticatedProjetosIdRoute,
  } as any)
const AuthenticatedProjetosIdGestaoRoute =
  AuthenticatedProjetosIdGestaoRouteImport.update({
    id: '/gestao',
    path: '/gestao',
    getParentRoute: () => AuthenticatedProjetosIdRoute,
  } as any)
const AuthenticatedProjetosIdExecucaoRoute =
  AuthenticatedProjetosIdExecucaoRouteImport.update({
    id: '/execucao',
    path: '/execucao',
    getParentRoute: () => AuthenticatedProjetosIdRoute,
  } as any)
const AuthenticatedProjetosIdEncerramentoRoute =
  AuthenticatedProjetosIdEncerramentoRouteImport.update({
    id: '/encerramento',
    path: '/encerramento',
    getParentRoute: () => AuthenticatedProjetosIdRoute,
  } as any)
const AuthenticatedProjetosIdDiagnosticoRoute =
  AuthenticatedProjetosIdDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedProjetosIdRoute,
  } as any)
const AuthenticatedProcessosSugerirInterviewIdRoute =
  AuthenticatedProcessosSugerirInterviewIdRouteImport.update({
    id: '/processos/sugerir/$interviewId',
    path: '/processos/sugerir/$interviewId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndicadoresIdColetarRoute =
  AuthenticatedIndicadoresIdColetarRouteImport.update({
    id: '/indicadores/$id/coletar',
    path: '/indicadores/$id/coletar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/c/$token': typeof CTokenRoute
  '/p/$token': typeof PTokenRoute
  '/causa-raiz/$id': typeof AuthenticatedCausaRaizIdRoute
  '/cronoanalise/$id': typeof AuthenticatedCronoanaliseIdRoute
  '/cronoanalise/nova': typeof AuthenticatedCronoanaliseNovaRoute
  '/diagnostico/$id': typeof AuthenticatedDiagnosticoIdRoute
  '/entrevistas/$id': typeof AuthenticatedEntrevistasIdRoute
  '/entrevistas/nova': typeof AuthenticatedEntrevistasNovaRoute
  '/fase/$slug': typeof AuthenticatedFaseSlugRoute
  '/mapas/decisao': typeof AuthenticatedMapasDecisaoRoute
  '/mapas/dores': typeof AuthenticatedMapasDoresRoute
  '/mapas/informacao': typeof AuthenticatedMapasInformacaoRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/projetos/$id': typeof AuthenticatedProjetosIdRouteWithChildren
  '/analise-critica/': typeof AuthenticatedAnaliseCriticaIndexRoute
  '/calendario/': typeof AuthenticatedCalendarioIndexRoute
  '/causa-raiz/': typeof AuthenticatedCausaRaizIndexRoute
  '/controle/': typeof AuthenticatedControleIndexRoute
  '/cronoanalise/': typeof AuthenticatedCronoanaliseIndexRoute
  '/diagnostico/': typeof AuthenticatedDiagnosticoIndexRoute
  '/entrevistas/': typeof AuthenticatedEntrevistasIndexRoute
  '/horas/': typeof AuthenticatedHorasIndexRoute
  '/indicadores/': typeof AuthenticatedIndicadoresIndexRoute
  '/oportunidades/': typeof AuthenticatedOportunidadesIndexRoute
  '/planos-acao/': typeof AuthenticatedPlanosAcaoIndexRoute
  '/priorizacao/': typeof AuthenticatedPriorizacaoIndexRoute
  '/processos/': typeof AuthenticatedProcessosIndexRoute
  '/projetos/': typeof AuthenticatedProjetosIndexRoute
  '/relatorio-acompanhamento/': typeof AuthenticatedRelatorioAcompanhamentoIndexRoute
  '/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
  '/roadmap/': typeof AuthenticatedRoadmapIndexRoute
  '/tobe/': typeof AuthenticatedTobeIndexRoute
  '/indicadores/$id/coletar': typeof AuthenticatedIndicadoresIdColetarRoute
  '/processos/sugerir/$interviewId': typeof AuthenticatedProcessosSugerirInterviewIdRoute
  '/projetos/$id/diagnostico': typeof AuthenticatedProjetosIdDiagnosticoRoute
  '/projetos/$id/encerramento': typeof AuthenticatedProjetosIdEncerramentoRoute
  '/projetos/$id/execucao': typeof AuthenticatedProjetosIdExecucaoRoute
  '/projetos/$id/gestao': typeof AuthenticatedProjetosIdGestaoRoute
  '/projetos/$id/mapeamento': typeof AuthenticatedProjetosIdMapeamentoRoute
  '/projetos/$id/melhorias': typeof AuthenticatedProjetosIdMelhoriasRoute
  '/api/public/coletas/$token': typeof ApiPublicColetasTokenRoute
  '/api/public/planos/$token': typeof ApiPublicPlanosTokenRoute
  '/projetos/$id/': typeof AuthenticatedProjetosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/c/$token': typeof CTokenRoute
  '/p/$token': typeof PTokenRoute
  '/causa-raiz/$id': typeof AuthenticatedCausaRaizIdRoute
  '/cronoanalise/$id': typeof AuthenticatedCronoanaliseIdRoute
  '/cronoanalise/nova': typeof AuthenticatedCronoanaliseNovaRoute
  '/diagnostico/$id': typeof AuthenticatedDiagnosticoIdRoute
  '/entrevistas/$id': typeof AuthenticatedEntrevistasIdRoute
  '/entrevistas/nova': typeof AuthenticatedEntrevistasNovaRoute
  '/fase/$slug': typeof AuthenticatedFaseSlugRoute
  '/mapas/decisao': typeof AuthenticatedMapasDecisaoRoute
  '/mapas/dores': typeof AuthenticatedMapasDoresRoute
  '/mapas/informacao': typeof AuthenticatedMapasInformacaoRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/analise-critica': typeof AuthenticatedAnaliseCriticaIndexRoute
  '/calendario': typeof AuthenticatedCalendarioIndexRoute
  '/causa-raiz': typeof AuthenticatedCausaRaizIndexRoute
  '/controle': typeof AuthenticatedControleIndexRoute
  '/cronoanalise': typeof AuthenticatedCronoanaliseIndexRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoIndexRoute
  '/entrevistas': typeof AuthenticatedEntrevistasIndexRoute
  '/horas': typeof AuthenticatedHorasIndexRoute
  '/indicadores': typeof AuthenticatedIndicadoresIndexRoute
  '/oportunidades': typeof AuthenticatedOportunidadesIndexRoute
  '/planos-acao': typeof AuthenticatedPlanosAcaoIndexRoute
  '/priorizacao': typeof AuthenticatedPriorizacaoIndexRoute
  '/processos': typeof AuthenticatedProcessosIndexRoute
  '/projetos': typeof AuthenticatedProjetosIndexRoute
  '/relatorio-acompanhamento': typeof AuthenticatedRelatorioAcompanhamentoIndexRoute
  '/relatorios': typeof AuthenticatedRelatoriosIndexRoute
  '/roadmap': typeof AuthenticatedRoadmapIndexRoute
  '/tobe': typeof AuthenticatedTobeIndexRoute
  '/indicadores/$id/coletar': typeof AuthenticatedIndicadoresIdColetarRoute
  '/processos/sugerir/$interviewId': typeof AuthenticatedProcessosSugerirInterviewIdRoute
  '/projetos/$id/diagnostico': typeof AuthenticatedProjetosIdDiagnosticoRoute
  '/projetos/$id/encerramento': typeof AuthenticatedProjetosIdEncerramentoRoute
  '/projetos/$id/execucao': typeof AuthenticatedProjetosIdExecucaoRoute
  '/projetos/$id/gestao': typeof AuthenticatedProjetosIdGestaoRoute
  '/projetos/$id/mapeamento': typeof AuthenticatedProjetosIdMapeamentoRoute
  '/projetos/$id/melhorias': typeof AuthenticatedProjetosIdMelhoriasRoute
  '/api/public/coletas/$token': typeof ApiPublicColetasTokenRoute
  '/api/public/planos/$token': typeof ApiPublicPlanosTokenRoute
  '/projetos/$id': typeof AuthenticatedProjetosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/c/$token': typeof CTokenRoute
  '/p/$token': typeof PTokenRoute
  '/_authenticated/causa-raiz/$id': typeof AuthenticatedCausaRaizIdRoute
  '/_authenticated/cronoanalise/$id': typeof AuthenticatedCronoanaliseIdRoute
  '/_authenticated/cronoanalise/nova': typeof AuthenticatedCronoanaliseNovaRoute
  '/_authenticated/diagnostico/$id': typeof AuthenticatedDiagnosticoIdRoute
  '/_authenticated/entrevistas/$id': typeof AuthenticatedEntrevistasIdRoute
  '/_authenticated/entrevistas/nova': typeof AuthenticatedEntrevistasNovaRoute
  '/_authenticated/fase/$slug': typeof AuthenticatedFaseSlugRoute
  '/_authenticated/mapas/decisao': typeof AuthenticatedMapasDecisaoRoute
  '/_authenticated/mapas/dores': typeof AuthenticatedMapasDoresRoute
  '/_authenticated/mapas/informacao': typeof AuthenticatedMapasInformacaoRoute
  '/_authenticated/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/_authenticated/projetos/$id': typeof AuthenticatedProjetosIdRouteWithChildren
  '/_authenticated/analise-critica/': typeof AuthenticatedAnaliseCriticaIndexRoute
  '/_authenticated/calendario/': typeof AuthenticatedCalendarioIndexRoute
  '/_authenticated/causa-raiz/': typeof AuthenticatedCausaRaizIndexRoute
  '/_authenticated/controle/': typeof AuthenticatedControleIndexRoute
  '/_authenticated/cronoanalise/': typeof AuthenticatedCronoanaliseIndexRoute
  '/_authenticated/diagnostico/': typeof AuthenticatedDiagnosticoIndexRoute
  '/_authenticated/entrevistas/': typeof AuthenticatedEntrevistasIndexRoute
  '/_authenticated/horas/': typeof AuthenticatedHorasIndexRoute
  '/_authenticated/indicadores/': typeof AuthenticatedIndicadoresIndexRoute
  '/_authenticated/oportunidades/': typeof AuthenticatedOportunidadesIndexRoute
  '/_authenticated/planos-acao/': typeof AuthenticatedPlanosAcaoIndexRoute
  '/_authenticated/priorizacao/': typeof AuthenticatedPriorizacaoIndexRoute
  '/_authenticated/processos/': typeof AuthenticatedProcessosIndexRoute
  '/_authenticated/projetos/': typeof AuthenticatedProjetosIndexRoute
  '/_authenticated/relatorio-acompanhamento/': typeof AuthenticatedRelatorioAcompanhamentoIndexRoute
  '/_authenticated/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
  '/_authenticated/roadmap/': typeof AuthenticatedRoadmapIndexRoute
  '/_authenticated/tobe/': typeof AuthenticatedTobeIndexRoute
  '/_authenticated/indicadores/$id/coletar': typeof AuthenticatedIndicadoresIdColetarRoute
  '/_authenticated/processos/sugerir/$interviewId': typeof AuthenticatedProcessosSugerirInterviewIdRoute
  '/_authenticated/projetos/$id/diagnostico': typeof AuthenticatedProjetosIdDiagnosticoRoute
  '/_authenticated/projetos/$id/encerramento': typeof AuthenticatedProjetosIdEncerramentoRoute
  '/_authenticated/projetos/$id/execucao': typeof AuthenticatedProjetosIdExecucaoRoute
  '/_authenticated/projetos/$id/gestao': typeof AuthenticatedProjetosIdGestaoRoute
  '/_authenticated/projetos/$id/mapeamento': typeof AuthenticatedProjetosIdMapeamentoRoute
  '/_authenticated/projetos/$id/melhorias': typeof AuthenticatedProjetosIdMelhoriasRoute
  '/api/public/coletas/$token': typeof ApiPublicColetasTokenRoute
  '/api/public/planos/$token': typeof ApiPublicPlanosTokenRoute
  '/_authenticated/projetos/$id/': typeof AuthenticatedProjetosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/empresas'
    | '/c/$token'
    | '/p/$token'
    | '/causa-raiz/$id'
    | '/cronoanalise/$id'
    | '/cronoanalise/nova'
    | '/diagnostico/$id'
    | '/entrevistas/$id'
    | '/entrevistas/nova'
    | '/fase/$slug'
    | '/mapas/decisao'
    | '/mapas/dores'
    | '/mapas/informacao'
    | '/processos/$id'
    | '/projetos/$id'
    | '/analise-critica/'
    | '/calendario/'
    | '/causa-raiz/'
    | '/controle/'
    | '/cronoanalise/'
    | '/diagnostico/'
    | '/entrevistas/'
    | '/horas/'
    | '/indicadores/'
    | '/oportunidades/'
    | '/planos-acao/'
    | '/priorizacao/'
    | '/processos/'
    | '/projetos/'
    | '/relatorio-acompanhamento/'
    | '/relatorios/'
    | '/roadmap/'
    | '/tobe/'
    | '/indicadores/$id/coletar'
    | '/processos/sugerir/$interviewId'
    | '/projetos/$id/diagnostico'
    | '/projetos/$id/encerramento'
    | '/projetos/$id/execucao'
    | '/projetos/$id/gestao'
    | '/projetos/$id/mapeamento'
    | '/projetos/$id/melhorias'
    | '/api/public/coletas/$token'
    | '/api/public/planos/$token'
    | '/projetos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/empresas'
    | '/c/$token'
    | '/p/$token'
    | '/causa-raiz/$id'
    | '/cronoanalise/$id'
    | '/cronoanalise/nova'
    | '/diagnostico/$id'
    | '/entrevistas/$id'
    | '/entrevistas/nova'
    | '/fase/$slug'
    | '/mapas/decisao'
    | '/mapas/dores'
    | '/mapas/informacao'
    | '/processos/$id'
    | '/analise-critica'
    | '/calendario'
    | '/causa-raiz'
    | '/controle'
    | '/cronoanalise'
    | '/diagnostico'
    | '/entrevistas'
    | '/horas'
    | '/indicadores'
    | '/oportunidades'
    | '/planos-acao'
    | '/priorizacao'
    | '/processos'
    | '/projetos'
    | '/relatorio-acompanhamento'
    | '/relatorios'
    | '/roadmap'
    | '/tobe'
    | '/indicadores/$id/coletar'
    | '/processos/sugerir/$interviewId'
    | '/projetos/$id/diagnostico'
    | '/projetos/$id/encerramento'
    | '/projetos/$id/execucao'
    | '/projetos/$id/gestao'
    | '/projetos/$id/mapeamento'
    | '/projetos/$id/melhorias'
    | '/api/public/coletas/$token'
    | '/api/public/planos/$token'
    | '/projetos/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/empresas'
    | '/c/$token'
    | '/p/$token'
    | '/_authenticated/causa-raiz/$id'
    | '/_authenticated/cronoanalise/$id'
    | '/_authenticated/cronoanalise/nova'
    | '/_authenticated/diagnostico/$id'
    | '/_authenticated/entrevistas/$id'
    | '/_authenticated/entrevistas/nova'
    | '/_authenticated/fase/$slug'
    | '/_authenticated/mapas/decisao'
    | '/_authenticated/mapas/dores'
    | '/_authenticated/mapas/informacao'
    | '/_authenticated/processos/$id'
    | '/_authenticated/projetos/$id'
    | '/_authenticated/analise-critica/'
    | '/_authenticated/calendario/'
    | '/_authenticated/causa-raiz/'
    | '/_authenticated/controle/'
    | '/_authenticated/cronoanalise/'
    | '/_authenticated/diagnostico/'
    | '/_authenticated/entrevistas/'
    | '/_authenticated/horas/'
    | '/_authenticated/indicadores/'
    | '/_authenticated/oportunidades/'
    | '/_authenticated/planos-acao/'
    | '/_authenticated/priorizacao/'
    | '/_authenticated/processos/'
    | '/_authenticated/projetos/'
    | '/_authenticated/relatorio-acompanhamento/'
    | '/_authenticated/relatorios/'
    | '/_authenticated/roadmap/'
    | '/_authenticated/tobe/'
    | '/_authenticated/indicadores/$id/coletar'
    | '/_authenticated/processos/sugerir/$interviewId'
    | '/_authenticated/projetos/$id/diagnostico'
    | '/_authenticated/projetos/$id/encerramento'
    | '/_authenticated/projetos/$id/execucao'
    | '/_authenticated/projetos/$id/gestao'
    | '/_authenticated/projetos/$id/mapeamento'
    | '/_authenticated/projetos/$id/melhorias'
    | '/api/public/coletas/$token'
    | '/api/public/planos/$token'
    | '/_authenticated/projetos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CTokenRoute: typeof CTokenRoute
  PTokenRoute: typeof PTokenRoute
  ApiPublicColetasTokenRoute: typeof ApiPublicColetasTokenRoute
  ApiPublicPlanosTokenRoute: typeof ApiPublicPlanosTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tobe/': {
      id: '/_authenticated/tobe/'
      path: '/tobe'
      fullPath: '/tobe/'
      preLoaderRoute: typeof AuthenticatedTobeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap/': {
      id: '/_authenticated/roadmap/'
      path: '/roadmap'
      fullPath: '/roadmap/'
      preLoaderRoute: typeof AuthenticatedRoadmapIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/': {
      id: '/_authenticated/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof AuthenticatedRelatoriosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio-acompanhamento/': {
      id: '/_authenticated/relatorio-acompanhamento/'
      path: '/relatorio-acompanhamento'
      fullPath: '/relatorio-acompanhamento/'
      preLoaderRoute: typeof AuthenticatedRelatorioAcompanhamentoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos/': {
      id: '/_authenticated/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof AuthenticatedProjetosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processos/': {
      id: '/_authenticated/processos/'
      path: '/processos'
      fullPath: '/processos/'
      preLoaderRoute: typeof AuthenticatedProcessosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/priorizacao/': {
      id: '/_authenticated/priorizacao/'
      path: '/priorizacao'
      fullPath: '/priorizacao/'
      preLoaderRoute: typeof AuthenticatedPriorizacaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos-acao/': {
      id: '/_authenticated/planos-acao/'
      path: '/planos-acao'
      fullPath: '/planos-acao/'
      preLoaderRoute: typeof AuthenticatedPlanosAcaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oportunidades/': {
      id: '/_authenticated/oportunidades/'
      path: '/oportunidades'
      fullPath: '/oportunidades/'
      preLoaderRoute: typeof AuthenticatedOportunidadesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicadores/': {
      id: '/_authenticated/indicadores/'
      path: '/indicadores'
      fullPath: '/indicadores/'
      preLoaderRoute: typeof AuthenticatedIndicadoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/horas/': {
      id: '/_authenticated/horas/'
      path: '/horas'
      fullPath: '/horas/'
      preLoaderRoute: typeof AuthenticatedHorasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrevistas/': {
      id: '/_authenticated/entrevistas/'
      path: '/entrevistas'
      fullPath: '/entrevistas/'
      preLoaderRoute: typeof AuthenticatedEntrevistasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostico/': {
      id: '/_authenticated/diagnostico/'
      path: '/diagnostico'
      fullPath: '/diagnostico/'
      preLoaderRoute: typeof AuthenticatedDiagnosticoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cronoanalise/': {
      id: '/_authenticated/cronoanalise/'
      path: '/cronoanalise'
      fullPath: '/cronoanalise/'
      preLoaderRoute: typeof AuthenticatedCronoanaliseIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/controle/': {
      id: '/_authenticated/controle/'
      path: '/controle'
      fullPath: '/controle/'
      preLoaderRoute: typeof AuthenticatedControleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/causa-raiz/': {
      id: '/_authenticated/causa-raiz/'
      path: '/causa-raiz'
      fullPath: '/causa-raiz/'
      preLoaderRoute: typeof AuthenticatedCausaRaizIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario/': {
      id: '/_authenticated/calendario/'
      path: '/calendario'
      fullPath: '/calendario/'
      preLoaderRoute: typeof AuthenticatedCalendarioIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analise-critica/': {
      id: '/_authenticated/analise-critica/'
      path: '/analise-critica'
      fullPath: '/analise-critica/'
      preLoaderRoute: typeof AuthenticatedAnaliseCriticaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos/$id': {
      id: '/_authenticated/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof AuthenticatedProjetosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processos/$id': {
      id: '/_authenticated/processos/$id'
      path: '/processos/$id'
      fullPath: '/processos/$id'
      preLoaderRoute: typeof AuthenticatedProcessosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapas/informacao': {
      id: '/_authenticated/mapas/informacao'
      path: '/mapas/informacao'
      fullPath: '/mapas/informacao'
      preLoaderRoute: typeof AuthenticatedMapasInformacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapas/dores': {
      id: '/_authenticated/mapas/dores'
      path: '/mapas/dores'
      fullPath: '/mapas/dores'
      preLoaderRoute: typeof AuthenticatedMapasDoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapas/decisao': {
      id: '/_authenticated/mapas/decisao'
      path: '/mapas/decisao'
      fullPath: '/mapas/decisao'
      preLoaderRoute: typeof AuthenticatedMapasDecisaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fase/$slug': {
      id: '/_authenticated/fase/$slug'
      path: '/fase/$slug'
      fullPath: '/fase/$slug'
      preLoaderRoute: typeof AuthenticatedFaseSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrevistas/nova': {
      id: '/_authenticated/entrevistas/nova'
      path: '/entrevistas/nova'
      fullPath: '/entrevistas/nova'
      preLoaderRoute: typeof AuthenticatedEntrevistasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrevistas/$id': {
      id: '/_authenticated/entrevistas/$id'
      path: '/entrevistas/$id'
      fullPath: '/entrevistas/$id'
      preLoaderRoute: typeof AuthenticatedEntrevistasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostico/$id': {
      id: '/_authenticated/diagnostico/$id'
      path: '/diagnostico/$id'
      fullPath: '/diagnostico/$id'
      preLoaderRoute: typeof AuthenticatedDiagnosticoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cronoanalise/nova': {
      id: '/_authenticated/cronoanalise/nova'
      path: '/cronoanalise/nova'
      fullPath: '/cronoanalise/nova'
      preLoaderRoute: typeof AuthenticatedCronoanaliseNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cronoanalise/$id': {
      id: '/_authenticated/cronoanalise/$id'
      path: '/cronoanalise/$id'
      fullPath: '/cronoanalise/$id'
      preLoaderRoute: typeof AuthenticatedCronoanaliseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/causa-raiz/$id': {
      id: '/_authenticated/causa-raiz/$id'
      path: '/causa-raiz/$id'
      fullPath: '/causa-raiz/$id'
      preLoaderRoute: typeof AuthenticatedCausaRaizIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos/$id/': {
      id: '/_authenticated/projetos/$id/'
      path: '/'
      fullPath: '/projetos/$id/'
      preLoaderRoute: typeof AuthenticatedProjetosIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjetosIdRoute
    }
    '/api/public/planos/$token': {
      id: '/api/public/planos/$token'
      path: '/api/public/planos/$token'
      fullPath: '/api/public/planos/$token'
      preLoaderRoute: typeof ApiPublicPlanosTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/coletas/$token': {
      id: '/api/public/coletas/$token'
      path: '/api/public/coletas/$token'
      fullPath: '/api/public/coletas/$token'
      preLoaderRoute: typeof ApiPublicColetasTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projetos/$id/melhorias': {
      id: '/_authenticated/projetos/$id/melhorias'
      path: '/melhorias'
      fullPath: '/projetos/$id/melhorias'
      preLoaderRoute: typeof AuthenticatedProjetosIdMelhoriasRouteImport
      parentRoute: typeof AuthenticatedProjetosIdRoute
    }
    '/_authenticated/projetos/$id/mapeamento': {
      id: '/_authenticated/projetos/$id/mapeamento'
      path: '/mapeamento'
      fullPath: '/projetos/$id/mapeamento'
      preLoaderRoute: typeof AuthenticatedProjetosIdMapeamentoRouteImport
      parentRoute: typeof AuthenticatedProjetosIdRoute
    }
    '/_authenticated/projetos/$id/gestao': {
      id: '/_authenticated/projetos/$id/gestao'
      path: '/gestao'
      fullPath: '/projetos/$id/gestao'
      preLoaderRoute: typeof AuthenticatedProjetosIdGestaoRouteImport
      parentRoute: typeof AuthenticatedProjetosIdRoute
    }
    '/_authenticated/projetos/$id/execucao': {
      id: '/_authenticated/projetos/$id/execucao'
      path: '/execucao'
      fullPath: '/projetos/$id/execucao'
      preLoaderRoute: typeof AuthenticatedProjetosIdExecucaoRouteImport
      parentRoute: typeof AuthenticatedProjetosIdRoute
    }
    '/_authenticated/projetos/$id/encerramento': {
      id: '/_authenticated/projetos/$id/encerramento'
      path: '/encerramento'
      fullPath: '/projetos/$id/encerramento'
      preLoaderRoute: typeof AuthenticatedProjetosIdEncerramentoRouteImport
      parentRoute: typeof AuthenticatedProjetosIdRoute
    }
    '/_authenticated/projetos/$id/diagnostico': {
      id: '/_authenticated/projetos/$id/diagnostico'
      path: '/diagnostico'
      fullPath: '/projetos/$id/diagnostico'
      preLoaderRoute: typeof AuthenticatedProjetosIdDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedProjetosIdRoute
    }
    '/_authenticated/processos/sugerir/$interviewId': {
      id: '/_authenticated/processos/sugerir/$interviewId'
      path: '/processos/sugerir/$interviewId'
      fullPath: '/processos/sugerir/$interviewId'
      preLoaderRoute: typeof AuthenticatedProcessosSugerirInterviewIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicadores/$id/coletar': {
      id: '/_authenticated/indicadores/$id/coletar'
      path: '/indicadores/$id/coletar'
      fullPath: '/indicadores/$id/coletar'
      preLoaderRoute: typeof AuthenticatedIndicadoresIdColetarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedProjetosIdRouteChildren {
  AuthenticatedProjetosIdDiagnosticoRoute: typeof AuthenticatedProjetosIdDiagnosticoRoute
  AuthenticatedProjetosIdEncerramentoRoute: typeof AuthenticatedProjetosIdEncerramentoRoute
  AuthenticatedProjetosIdExecucaoRoute: typeof AuthenticatedProjetosIdExecucaoRoute
  AuthenticatedProjetosIdGestaoRoute: typeof AuthenticatedProjetosIdGestaoRoute
  AuthenticatedProjetosIdMapeamentoRoute: typeof AuthenticatedProjetosIdMapeamentoRoute
  AuthenticatedProjetosIdMelhoriasRoute: typeof AuthenticatedProjetosIdMelhoriasRoute
  AuthenticatedProjetosIdIndexRoute: typeof AuthenticatedProjetosIdIndexRoute
}

const AuthenticatedProjetosIdRouteChildren: AuthenticatedProjetosIdRouteChildren =
  {
    AuthenticatedProjetosIdDiagnosticoRoute:
      AuthenticatedProjetosIdDiagnosticoRoute,
    AuthenticatedProjetosIdEncerramentoRoute:
      AuthenticatedProjetosIdEncerramentoRoute,
    AuthenticatedProjetosIdExecucaoRoute: AuthenticatedProjetosIdExecucaoRoute,
    AuthenticatedProjetosIdGestaoRoute: AuthenticatedProjetosIdGestaoRoute,
    AuthenticatedProjetosIdMapeamentoRoute:
      AuthenticatedProjetosIdMapeamentoRoute,
    AuthenticatedProjetosIdMelhoriasRoute:
      AuthenticatedProjetosIdMelhoriasRoute,
    AuthenticatedProjetosIdIndexRoute: AuthenticatedProjetosIdIndexRoute,
  }

const AuthenticatedProjetosIdRouteWithChildren =
  AuthenticatedProjetosIdRoute._addFileChildren(
    AuthenticatedProjetosIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedCausaRaizIdRoute: typeof AuthenticatedCausaRaizIdRoute
  AuthenticatedCronoanaliseIdRoute: typeof AuthenticatedCronoanaliseIdRoute
  AuthenticatedCronoanaliseNovaRoute: typeof AuthenticatedCronoanaliseNovaRoute
  AuthenticatedDiagnosticoIdRoute: typeof AuthenticatedDiagnosticoIdRoute
  AuthenticatedEntrevistasIdRoute: typeof AuthenticatedEntrevistasIdRoute
  AuthenticatedEntrevistasNovaRoute: typeof AuthenticatedEntrevistasNovaRoute
  AuthenticatedFaseSlugRoute: typeof AuthenticatedFaseSlugRoute
  AuthenticatedMapasDecisaoRoute: typeof AuthenticatedMapasDecisaoRoute
  AuthenticatedMapasDoresRoute: typeof AuthenticatedMapasDoresRoute
  AuthenticatedMapasInformacaoRoute: typeof AuthenticatedMapasInformacaoRoute
  AuthenticatedProcessosIdRoute: typeof AuthenticatedProcessosIdRoute
  AuthenticatedProjetosIdRoute: typeof AuthenticatedProjetosIdRouteWithChildren
  AuthenticatedAnaliseCriticaIndexRoute: typeof AuthenticatedAnaliseCriticaIndexRoute
  AuthenticatedCalendarioIndexRoute: typeof AuthenticatedCalendarioIndexRoute
  AuthenticatedCausaRaizIndexRoute: typeof AuthenticatedCausaRaizIndexRoute
  AuthenticatedControleIndexRoute: typeof AuthenticatedControleIndexRoute
  AuthenticatedCronoanaliseIndexRoute: typeof AuthenticatedCronoanaliseIndexRoute
  AuthenticatedDiagnosticoIndexRoute: typeof AuthenticatedDiagnosticoIndexRoute
  AuthenticatedEntrevistasIndexRoute: typeof AuthenticatedEntrevistasIndexRoute
  AuthenticatedHorasIndexRoute: typeof AuthenticatedHorasIndexRoute
  AuthenticatedIndicadoresIndexRoute: typeof AuthenticatedIndicadoresIndexRoute
  AuthenticatedOportunidadesIndexRoute: typeof AuthenticatedOportunidadesIndexRoute
  AuthenticatedPlanosAcaoIndexRoute: typeof AuthenticatedPlanosAcaoIndexRoute
  AuthenticatedPriorizacaoIndexRoute: typeof AuthenticatedPriorizacaoIndexRoute
  AuthenticatedProcessosIndexRoute: typeof AuthenticatedProcessosIndexRoute
  AuthenticatedProjetosIndexRoute: typeof AuthenticatedProjetosIndexRoute
  AuthenticatedRelatorioAcompanhamentoIndexRoute: typeof AuthenticatedRelatorioAcompanhamentoIndexRoute
  AuthenticatedRelatoriosIndexRoute: typeof AuthenticatedRelatoriosIndexRoute
  AuthenticatedRoadmapIndexRoute: typeof AuthenticatedRoadmapIndexRoute
  AuthenticatedTobeIndexRoute: typeof AuthenticatedTobeIndexRoute
  AuthenticatedIndicadoresIdColetarRoute: typeof AuthenticatedIndicadoresIdColetarRoute
  AuthenticatedProcessosSugerirInterviewIdRoute: typeof AuthenticatedProcessosSugerirInterviewIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedCausaRaizIdRoute: AuthenticatedCausaRaizIdRoute,
  AuthenticatedCronoanaliseIdRoute: AuthenticatedCronoanaliseIdRoute,
  AuthenticatedCronoanaliseNovaRoute: AuthenticatedCronoanaliseNovaRoute,
  AuthenticatedDiagnosticoIdRoute: AuthenticatedDiagnosticoIdRoute,
  AuthenticatedEntrevistasIdRoute: AuthenticatedEntrevistasIdRoute,
  AuthenticatedEntrevistasNovaRoute: AuthenticatedEntrevistasNovaRoute,
  AuthenticatedFaseSlugRoute: AuthenticatedFaseSlugRoute,
  AuthenticatedMapasDecisaoRoute: AuthenticatedMapasDecisaoRoute,
  AuthenticatedMapasDoresRoute: AuthenticatedMapasDoresRoute,
  AuthenticatedMapasInformacaoRoute: AuthenticatedMapasInformacaoRoute,
  AuthenticatedProcessosIdRoute: AuthenticatedProcessosIdRoute,
  AuthenticatedProjetosIdRoute: AuthenticatedProjetosIdRouteWithChildren,
  AuthenticatedAnaliseCriticaIndexRoute: AuthenticatedAnaliseCriticaIndexRoute,
  AuthenticatedCalendarioIndexRoute: AuthenticatedCalendarioIndexRoute,
  AuthenticatedCausaRaizIndexRoute: AuthenticatedCausaRaizIndexRoute,
  AuthenticatedControleIndexRoute: AuthenticatedControleIndexRoute,
  AuthenticatedCronoanaliseIndexRoute: AuthenticatedCronoanaliseIndexRoute,
  AuthenticatedDiagnosticoIndexRoute: AuthenticatedDiagnosticoIndexRoute,
  AuthenticatedEntrevistasIndexRoute: AuthenticatedEntrevistasIndexRoute,
  AuthenticatedHorasIndexRoute: AuthenticatedHorasIndexRoute,
  AuthenticatedIndicadoresIndexRoute: AuthenticatedIndicadoresIndexRoute,
  AuthenticatedOportunidadesIndexRoute: AuthenticatedOportunidadesIndexRoute,
  AuthenticatedPlanosAcaoIndexRoute: AuthenticatedPlanosAcaoIndexRoute,
  AuthenticatedPriorizacaoIndexRoute: AuthenticatedPriorizacaoIndexRoute,
  AuthenticatedProcessosIndexRoute: AuthenticatedProcessosIndexRoute,
  AuthenticatedProjetosIndexRoute: AuthenticatedProjetosIndexRoute,
  AuthenticatedRelatorioAcompanhamentoIndexRoute:
    AuthenticatedRelatorioAcompanhamentoIndexRoute,
  AuthenticatedRelatoriosIndexRoute: AuthenticatedRelatoriosIndexRoute,
  AuthenticatedRoadmapIndexRoute: AuthenticatedRoadmapIndexRoute,
  AuthenticatedTobeIndexRoute: AuthenticatedTobeIndexRoute,
  AuthenticatedIndicadoresIdColetarRoute:
    AuthenticatedIndicadoresIdColetarRoute,
  AuthenticatedProcessosSugerirInterviewIdRoute:
    AuthenticatedProcessosSugerirInterviewIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CTokenRoute: CTokenRoute,
  PTokenRoute: PTokenRoute,
  ApiPublicColetasTokenRoute: ApiPublicColetasTokenRoute,
  ApiPublicPlanosTokenRoute: ApiPublicPlanosTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
